#数据源配置
spring:
  datasource:
    url: jdbc:mysql://www.drjjdh.cn:3506/daichao?useUnicode=true&characterEncoding=utf8
    username: root
    password: shen@liu
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    database: 1
    password:
    port: 6379
    enabled: true

logging:
  config: "classpath:logback-api.xml"
  console: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p ${PID:-} [%15.15t] %-40.40logger{39} : %m%n"
  level.root: debug

#赛邮短信
saiyou:
  account: hangzhouyoudai@foxmail.com
  password: nbly1216@
  templateId:
    #注册模板
    registerMsgId: zcOWs2
    #拒绝模板
    refuseMsgId: SoElO1
    #放款短信提醒
    payMoneyMsgId: FYTLL1
    #用户还款成功短信
    repaySuccessMsgId: ZfWzi1
    #提额提醒
    addMoneyMsgId: T8NVA3
    #还款时间前6小时提醒
    repayDay6HoureMsgId: X80oW
    #还款日前1天提醒
    repay1DayMsgId: 0vzWL
    #还款日前2天提醒
    repay2DayMsgId: Melbc4
    #还款日当天提醒
    repayDayMsgId: hfGw71
    #逾期提醒
    overdueMsgId: 2im7X4

product_folder: daichaoApi/userOption

#跳转H5地址
jump_url: http://test.dcapi.hzyoudai.com/risk/index.html
#黑网检测地址
check_url: http://test.risk.hzyoudai.com/api/riskModule/check
#请求认证报告地址
select_report_url: http://test.risk.hzyoudai.com/api/riskModule/selectReport
#查询检测记录
select_check_record_url: http://test.risk.hzyoudai.com/api/riskModule/selectCheckRecord
#支付宝回调地址
ali_notify_url: http://test.dcapi.hzyoudai.com/api/notify/aliNotify
#微信回调地址
wx_notify_url: http://2432j322y3.qicp.vip:58469/api/notify/wxNotify

