#数据源配置
spring:
  datasource:
    url: jdbc:mysql://47.96.70.228:3306/daichao?useUnicode=true&characterEncoding=utf8
    username: root
    password: eGnlC^Lkty&iTCO8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.96.70.228
    database: 1
    password: FTCJk^xMJy#RsLAR
    port: 6379
    enabled: true


product_folder: daichao/product
